name: Node.js Build and Deploy

on:
  push:
    branches: [ "main" ]

env:
  NODEJS_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/node-js-image:${{ github.sha }}

jobs:
  build-node-js:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Nodejs
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ env.NODEJS_IMAGE }}
    
  update-yc:
    runs-on: ubuntu-latest
    needs: [build-node-js]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Deploy COI VM
      uses: yc-actions/yc-coi-deploy@v1.0.1
      env:
        BACKEND_IMAGE: ${{ env.NODEJS_IMAGE }}
        YC_VM_SSH: ${{ secrets.YC_VM_SSH }}
        YC_VM_USERNAME: ${{ secrets.YC_VM_USERNAME }}
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        folder-id: ${{ secrets.YC_FOLDER_ID }}
        VM-name: ${{ secrets.YC_VM_NAME }}
        vm-service-account-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
        vm-cores: 2
        vm-platform-id: 'standard-v2'
        vm-memory: 512Mb
        vm-disk-size: 30Gb
        vm-core-fraction: 5
        vm-subnet-id: ${{ secrets.YC_SUBNET_ID }}
        docker-compose-path: './yandex-cloud/docker-compose.yaml'
        user-data-path: './yandex-cloud/cloud-config.yaml'
        